# Generated by Django 5.1.6 on 2025-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=50, unique=True)),
                ('body', models.TextField()),
                ('score', models.IntegerField()),
                ('subreddit', models.CharField(max_length=100)),
                ('created_utc', models.DateTimeField()),
                ('parent_id', models.CharField(max_length=50)),
                ('link_id', models.CharField(max_length=50)),
                ('permalink', models.URLField()),
                ('edited', models.BooleanField(default=False)),
            ],
        ),
    ]
