# Generated by Django 5.1.6 on 2025-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditcomment',
            name='id',
        ),
        migrations.AddField(
            model_name='redditcomment',
            name='awards',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='redditcomment',
            name='comment_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='redditcomment',
            name='created_utc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='redditcomment',
            name='link_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='redditcomment',
            name='parent_id',
            field=models.CharField(max_length=100),
        ),
    ]
